
name: npm publish

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare yarn@4.12.0 --activate
        yarn --version

    - uses: calcit-lang/setup-cr@0.0.9

    - name: "compiles to js"
      run: >
        caps --ci
        && yarn install --immutable
        && cr js
        && yarn compile-server
        && yarn vite build --base=./

    - name: publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
